SHOW DATABASES;

DROP DATABASE mevo;
CREATE DATABASE IF NOT EXISTS mevo;
USE mevo;

CREATE TABLE clubs (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` varchar(50) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sessions (
    `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` varchar(50) NOT NULL,
    occured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS shots (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  ball_speed FLOAT,
  club_speed FLOAT,
  smash FLOAT,
  carry FLOAT,
  launch_angle FLOAT,
  spin INT,
  height FLOAT,
  flight_time FLOAT,
  club VARCHAR(100),
  session_id TINYINT UNSIGNED NOT NULL,
  club_id TINYINT UNSIGNED NOT NULL,
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE ON UPDATE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SHOW TABLES;

DESCRIBE shots;
DESCRIBE clubs;
DESCRIBE sessions;

